apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 10Gi  # Specify the storage capacity
  volumeMode: Filesystem  # Can be Block or Filesystem
  accessModes:
    - ReadWriteOnce  # Choose the appropriate access mode (e.g., ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Can be Retain, Recycle, or Delete
  storageClassName: opk-sc  # Specify the storage class name
  hostPath:
    path: /data  # Specify the host path where the volume will be mounted
